// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJG9uWrPBUDLXVBhy-ne_QhUyE1xdVC_M',
    appId: '1:238152756643:web:0a4d8252764a3850c4fe16',
    messagingSenderId: '238152756643',
    projectId: 'bobashop-e2b35',
    authDomain: 'bobashop-e2b35.firebaseapp.com',
    storageBucket: 'bobashop-e2b35.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcLQ5h2glkKeR2U8ymj6vY5Ewh6DYTibA',
    appId: '1:238152756643:android:289ef98dd91808f0c4fe16',
    messagingSenderId: '238152756643',
    projectId: 'bobashop-e2b35',
    storageBucket: 'bobashop-e2b35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5NYtorYX0lZTmk0g_--aACkAeb6U8c6Q',
    appId: '1:238152756643:ios:7e3e5eefe0ed5fe4c4fe16',
    messagingSenderId: '238152756643',
    projectId: 'bobashop-e2b35',
    storageBucket: 'bobashop-e2b35.appspot.com',
    iosClientId: '238152756643-031tq8565s33p8lnrsajh1df8f6gf2mj.apps.googleusercontent.com',
    iosBundleId: 'Robin.Do',
  );
}
